language: node_js
node_js:
- 4.2.1
sudo: false
deploy:
  provider: npm
  email: sysadmin@coreybutler.com
  api_key:
    secure: mEX6vhPaVAl2W3V84CVnL/zu4CbcCp8eqEza4g+Ns41IFFW+SkM+wLkbmmlsogNLoXFPKMCrHnpQOxugEGKwTQ/3UQUuTW1FDP8rD6zX4UzY5aSRILcICSKWdlHa24mFjz2EYLTk+iIl35sTTEi+RAm2BPLk8RWWo/xhkZbOhH80zGXI3kCjYEadDBkYZ/dPOkJjNXuq69ejScAcnavM83OCSijdXYZ5V4Lc/G3E1wHMx6wJtXl81oro+/RqUJt/MH3Juuxb5CEIOHMdBpLlYjj9RFoh2t0tnt7dgfDxDUSeJIKJIUbuOVo9/Bk4pyXZ2N8CFb/RqgjM8cpTNyKk4mB8TfReWwUlrgSkZyy4lRFfpCJZvAR2xKPlzi1emf0Fz6fD2EDReEgdIakTkyj5BDpkyVoKas9QlqbY1oQNY0M0WjG4Rq0Tw818ycguxN4qgCRUlesWzbpiOIQ7rwY2iacs+kPEqvCnOiV3vSlqQkpxvbyRJnds1vD6PEsJpS+iLs6iodOni5mUcN8xkqZD6tEkpOdNT+JRo9nYU+SRb6nfnju7/40y+StxeeFlEPAcYvVb1P2NTkZ0MES9BnUR+8PEac54IICnJxAkeiVcHelpfxjcZ+JSeyBVj851voynlI4Bi7ytNa/NHFVo2YoCj0ZmfEqUggk5OadvOQXewJ8=
  on:
    tags: true
cache:
  directories:
  - node_modules
notifications:
  hipchat:
    rooms:
      secure: Ne08i/qfAlVkoBCmZK4hGH4MRhS4wKDP5XjEjboQRDgp6LYdY2AXbYfh/nYVx4VSb9RCNpYn/jSXfxWXvC7wV7zA/tUujJB53r8ZKa3L6JjYjs1xl3HLIeAKt+FU9atO5bFhwqqU4pJTwxei5QVSu2Fwpd2/E+3s6JmWag7Cq6JI9BJP6y3DC0U0zkKJDAdKnWjy2ISq+q3Wlvjk6omyfkfW40rVQhrw0TNoJImDhOaTUtEx9o2B5P8NRl3OXytIzxb/abrMEb4iqdXCmn3fj+CSVmoot5/jBueuc4NkgcRuIskyuu3ioaqTOWE0Mile/NrhxY7Y4FHuNU+FT9+PrVs6gvMWqeG6frBzArF4zdx3C5TaGXN3o+ZzO6vjrwHfXUEwrtIHgBRbIiuMyoDvGRzdteir63n4KsDPrU0APjGkDkj2J/burrbIG35pHvUmd8c5cppSRORxsGGwgEcTxwQhPlBgy5H7FD0Mk4jST9u2Rbh+dU/Gk8sbbkIkrnGCdKkbIsFtRyEyq5ng7tfUqvnPyrZlGh6GCw5E5Y9H1vMRMvmvk1m4R/uAS3Rz9EYJKd/Ip7qreQwQSFckIvlFF/ntJDV7DJeaKjd61/CiLJRnOb7BlRtQUr8LFvsjr3g/a0/OM5AV+edsHAMmodoOFg8n1V6X8HnN92IVmx6gBY8=
